name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"  # Mejor formato para rango de versiones

dependencies:  # Las dependencias principales van aquí
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  sidebarx: ^0.17.1
  hawk_fab_menu: ^1.2.0
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  webview_flutter_android: ^4.7.0

dev_dependencies:  # Solo herramientas de desarrollo aquí
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/botoninicio.json
    - assets/carga.json
    - assets/logo.png
    # Nota: Este comentario estaba mal colocado
    # Accede a los recursos de esta carpeta (imágenes)